include(InstallRequiredSystemLibraries)
set(CPACK_PACKAGE_FILE_NAME "solver")
set(CPACK_PACKAGE_CONTACT mayka29000@mail.ru)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "C++ project for equations ")
set(CPACK_DMG_VOLUME_NAME "solver-macos")
set(CPACK_DEBIAN_PACKAGE_NAME "solver-deb")
set(CPACK_RPM_PACKAGE_NAME "solver-rpm") 
set(CPACK_WIX_PACKAGE_NAME "solver-wix")
